pkgs.manifest
This updates SYBASE to point to /soft/SYBASE15.7.
(minor version 2.00 skipped as used in testing for different update)
=> Update CXC-Envs-Flight from 1.99 to 2.01

cfg/python_modules.cfg, pkgs.manifest
@jeanconn - do you have a problem with this?
I checked and it appears the only thing using stevedore is virtualenvwrapper.
"checked" means grepping for stevedore in every *.py file in the CentOS-5 build directory.
=> Remove virtualenv, virtualenvwrapper and stevedore

Makefile.in, cfg/anaconda-32.cfg, cfg/anaconda-64.cfg, cfg/git.cfg, cfg/gtk.cfg, cfg/perl_modules.cfg, cfg/python_modules.cfg, pkgs.conda, pkgs.manifest
Add tweaks to fix failed 0.18 tests
Includes reverted numexpr 2.2.2 to deal with 'copy_args' problems from hd5 queries.
Includes fontconfig/matplotlib updates for gtk to work for gui_fit.py
=> Add tweaks to fix failed 0.18 tests

cfg/xtime.cfg, pkgs.manifest
Bring in 2015 leapsec update to C lib and Perl
The Chandra::Time package just needed an update for a broken test due to the
new leapsec.
=> Bring in 2015 leapsec update to C lib and Perl

pkgs.manifest
Update xija and chandra_models.  This adds the roll support to xija for the updated dpa model and includes updated model specs in chandra_models.  HEAD/master is best served with its own PR for this as master has already diverged from the GRETA-appropriate candidate/build that includes these updates already.
=> Update xija and chandra_models

pkgs.manifest
Update mica to 0.5.3
This gets the starcheck parsing for starcheck 11.6.
=> Update mica to 0.5.3

NOTES.fix-egg-installs, cfg/python_modules.cfg
Pip is the (latest) modern way to install a package from a local source directory.  The rationale is that setuptools is the current modern way to do things in setup.py, but it has an annoying feature of insisting on installing via eggs and putting that into easy-install.pth.  That then makes it *impossible* to override the system-installed version via PYTHONPATH.  This is a long-standing feature that setuptools won't fix.
Enter pip, which takes an end run around this by installing packages in the "normal" way but writes an appropriate info file so that conda and pip can reliably uninstall.  (You don't get this with `python setup.py install`).
But... for a namespace package you still need to do an egg install, and PYTHONPATH will never work on those, but at least the local version in the …
=> Use pip to install instead of python setup.py install

pkgs.manifest
Update Ska-Web to 0.03 from 0.02
This update to Ska-Web saves remote timestamps for fetched files.
=> Update Ska-Web to 0.03 from 0.02

cfg/python_modules.cfg
It appears that the `--ignore-installed` option is taken quite literally and the previous version is not removed.  This is potentially dangerous and also leaves the old egg-info file around, which ends up confusing `conda list`.  (And then messes up ska_testr understanding of what is installed).
There was a reason I put this there, but it might have been from past experience of having pip annoyingly refuse to install something, reporting that the dependency is already satisfied.
@jeanconn - thoughts?  My feeling is to go ahead with this until we discover a reason otherwise.
=> Remove --ignore-installed from pip install

cfg/perl_modules.cfg, pkgs.manifest
Add Crypt::SSLeay to support https URLs.
This is largely for https support in LWP::UserAgent for Replan Central.
=> Add Crypt::SSLeay

pkgs.manifest
Update mica to 3.9.0
This mica version includes updates to mica.starcheck to fix Py3 issues, adds the individual star acquisition probabilities from the starcheck output to the database, and implements enhancements to the kadi app that displays star information and star observation histories.
=> Update mica to 3.9.0

pkgs.manifest
Update agasc module to 3.5.  This version brings back support for use of different agasc files.
=> Update agasc module to 3.5

template/include/cfg/10_define_impska.py
This updates the startup template file `10_define_impska.py` to use the modern IPython API for doing this.  It is compatible with the current flight Ska IPython.
Testing: I have had this in my `profile_default/startup` since working on the Py3 branch.
=> Update startup 10_define_impska.py to use modern API

pkgs.manifest
This installs mica 3.10.1 which includes a fix to handle fewer than 8 image windows commanded/used during an observation.  The code was already set to handle windows removed during processing, but was not configured to handle an "uncommanded" slot/window.  The error caused by this bug is preventing vv processing from continuing, so this is a somewhat time critical patch.  An issue has been opened on mica https://github.com/sot/mica/issues/128 to update processing such that a similar error would not stop overall processing.
=> Update mica to 3.10.1 (vv bugfix)

prune_packages.py
This can help a bit with rsyncing packages to other installations.
=> Add utility to prune old versions from /proj/sot/ska/pkgs

pkgs.manifest
Update to kadi 3.14.0 which includes the new break down of one shots per axis
=> Update to kadi 3.14.0

cfg/anaconda-32.cfg, cfg/anaconda-64.cfg
Add cmd to save/export conda env to prefix_arch
This makes a yaml file that could be used to try to reproduce an environment (though actually using the file has not been thoroughly tested in skare).
=> Add cmd to save/export conda env to prefix_arch

pkgs.manifest
Mica 3.12 includes:
- new access to attitudes from mica.archive.asp_l1 via `get_atts` and `get_atts_from_files`.
- improvements to guide stats calculations
- new warnings for acquisition anomalies discovered in processing
- simplification of mica.reports
=> Update mica to version 3.12

cfg/python_modules.cfg, pkgs.manifest
This brings the `py3` branch up to date with `master` and adds one more commit from #151 to install kadi 3.15.  In doing this I cherry-picked all the new non-merge commits.
=> Py3 catchup

pkgs.manifest
At present this is for installing kadi 3.15 to Ska test.
=> Update kadi from 3.14.1 to 3.15.2

cfg/python_modules.cfg, pkgs.manifest
These are the module changes approved at load review on 15-Mar-2018.
=> ACIS updates for backstop history / nlet support

pkgs.manifest
Making this a PR for better visibility.
=> Add acis_taco 4.0.  Replaces Chandra.taco, which will later be removed.

NOTES/NOTES.test-2.18-r561-5120035.rst
Update notes after skadev install for Matlab 2018068 release.  
This PR is separate from the pull request to update the tools as we generally update master with the notes even if the changes are in the greta branch.
=> Notes after skadev install for Matlab 2018068 release

cfg/anaconda-32.cfg, cfg/anaconda-64.cfg
Explicitly downgrade pycrypto to older/working 'build'
This fixes Ska.ftp errors like:
```
>                   raise e
E                   ValueError: CTR mode needs counter parameter, not IV
```
Not sure if it makes sense to do this or to try to upgrade conda packages to get the newer version that also fixes this.  Thought this might be a reasonable minimal change.
=> Explicitly downgrade pycrypto to older/working 'build'

pkgs.manifest
This includes changes to cmd_states and kadi to support that WSVIDALLDN sets ccd_count to 0.
There's also a new version of acis_thermal_check that uses the sqlite database by default instead of Sybase.
=> ACIS updates approved 31-Aug-2018

pkgs.manifest
This includes:
- update to xija to support the ACA model with the time-step-power
- update to chandra_aca with new drift model
- update to chandra_models with the updated ACA model
- update to starcheck to use the new ACA model
=> Post 2018:283 safe mode updates
