Makefile.in, cfg/anaconda-32.cfg, cfg/anaconda-64.cfg, cfg/python_modules.cfg, install.py, pkgs.conda
Remove the gtk components and fixes from the standard skare build.
=> Remove gtk components of build

Makefile.in, cfg/python_modules.cfg, pkgs.conda, pkgs.manifest
Use a source build of hdf5 1.8.7 instead of a conda-provided version
=> Hdf5 1.8.7

NOTES.test-0.18.rst
Add post-install HEAD testing notes
=> Add post-install HEAD testing notes

pkgs.conda
Add python packages to support saving jpegs
=> Add python packages to support saving jpegs

cfg/python_modules.cfg, pkgs.manifest
Add mica at (new) version 0.5
Previously installed but not managed from skare.
=> Add mica at version 0.5

install.py
This is a safe way to do `./install.py --config=python_modules --prefix=..` so that no unintended updates get done.
=> Add --confirm option to confirm prior to installing package(s)

pkgs.manifest
Update chandra_aca from 0.4 to 0.5
=> Update chandra_aca from 0.4 to 0.5

pkgs.manifest
=> Update mica to 0.5.1 from 0.5

NOTES.test-0.18-r542-f3fe1d4.rst
Add notes for 2015_351 / r542 GRETA build
=> Add notes for 2015_351 build

pkgs.manifest
Update chandra_aca from 0.5.1 to 0.6
=> Update chandra_aca from 0.5.1 to 0.6

pkgs.manifest
Update parse_cm to version 0.3 from 0.2
=> Update parse_cm to version 0.3 from 0.2

pkgs.manifest
Doing this as a PR for visibility.  This might be a good things for some higher-profile updates to Skare.
=> Update chandra_models from 0.9 to 0.10

cfg/python_modules.cfg, pkgs.manifest
GRETA ska environment updates for matlab tools release 2016_332
=> GRETA ska environment updates for matlab tools release 2016_332

pkgs.manifest
Update XTime and Chandra::Time for leap second.
Update Chandra.Time for leap second and improved testing.
=> Update head time packages

pkgs.manifest
=> Update chandra_models to 0.11

pkgs.manifest
=> Update chandra_aca to 0.8

pkgs.manifest
=> Update to starcheck 11.13

pkgs.manifest
=> Update mica to bugfix 3.7.2

pkgs.manifest
Update mica to version 3.8.0 from 3.7.2
=> Update mica to version 3.8.0 from 3.7.2

pkgs.manifest
=> Update maude to 3.1

pkgs.manifest
Update starcheck to version 11.15
=> Update starcheck to version 11.15

NOTES.test-0.18-r554-c27b973.rst
Update 2016 322 notes through pre-flight GRETA install
=> Update 2016 322 notes through pre-flight GRETA install

pkgs.manifest
Update to starcheck 11.17 and parse_cm 3.3.2
=> Update to starcheck 11.17 and parse_cm 3.3.2

pkgs.manifest
Update Chandra.cmd_states to 3.11 (conditionally skip Sybase tests)
=> Update Chandra.cmd_states to 3.11 (cond. skip Sybase tests)

pkgs.manifest
Update to mica 3.11 with doc update
=> Update to mica 3.11 with doc update

cfg/python_modules.cfg, pkgs.manifest
=> Add tables3_api package

pkgs.manifest
Update find_attitude to 0.2 (still not Py3-compat)
=> Update find_attitude to 0.2 (still not Py3-compat)

pkgs.manifest
Update chandra_aca to 3.13 and starcheck to 11.18
=> Update chandra_aca to 3.13 and starcheck to 11.18

pkgs.manifest
Update mica with report bugfix and bugfix (oversight) adding new methods to api docs
=> Update mica to bugfix 3.12.1

pkgs.manifest
Update chandra_aca to 3.14 with centroid residuals
=> Update chandra_aca to 3.14 with centroid residuals

pkgs.manifest
=> Update chandra_aca from 3.14 to 3.14.1

pkgs.manifest
=> Update xija to 3.8

pkgs.manifest
=> Update starcheck to 11.19

pkgs.manifest
Update xija to version 3.8 for GRETA
=> Update xija  on GRETA to version 3.8

cfg/python_modules.cfg, pkgs.manifest
Add ACIS thermal check tools and supporting package to skare
=> Add ACIS thermal check tools and supporting package to skare

pkgs.manifest
Include accompanying changes to hopper (0.3) and Chandra.Maneuver (3.7)
=> Update starcheck to version 11.23

pkgs.manifest
ACIS thermal model updates approved 07-Feb-2018.
=> ACIS thermal model updates approved 07-Feb-2018

pkgs.manifest
This update includes backstop_history 1.1.0 and acis_thermal_check 2.5.0 .
=> ACIS tools updates approved on 29-Mar-2018

pkgs.manifest
Update chandra_aca to version with spline acq probability model.
=> Update to spline acq probability model (starcheck 11.25)

pkgs.manifest
Update xija to 3.10 for acis_taco
=> Update xija to 3.10 for acis_taco

pkgs.manifest
Update maude to version 3.2 to support MAUDE 1.0
=> Update maude to version 3.2 to support MAUDE 1.0

pkgs.manifest
Updates to dpa_check, dea_check, psmc_check for July 2018 recalibration
=> Updates to dpa_check, dea_check, psmc_check for July 2018 recalibration

NOTES/NOTES.test-2.18-r561-5120035.rst
Update notes after ska flight install for Matlab 2018068 release
=> Update notes after ska flight install for Matlab 2018068 release

pkgs.manifest
=> Update to kadi 3.16

pkgs.manifest
Update starcheck to 11.27 with AGASC 1.7
=> Update starcheck to 11.27 with AGASC 1.7

pkgs.manifest
=> Update mica to 3.15

pkgs.manifest
Updates for aimpoint and ACA model refinement post 2018:283 safe mode.
=> Safe mode fixes

pkgs.manifest
=> Update kadi to 3.16.4

pkgs.manifest
=> Update mica to 3.17
